# Elasticsearch 6.8.4

FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.4

# The upstream image was built by:
#   https://github.com/elastic/dockerfiles/tree/v6.8.4/elasticsearch

# For a full list of supported images and tags visit https://www.docker.elastic.co

# For Elasticsearch documentation visit https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

# See https://github.com/docker-library/official-images/pull/4916 for more details.
